name: jam
description: "A Food Rescue Flutter application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  google_maps_flutter: ^2.2.3
  flutter_typeahead: ^4.1.0
  http: ^1.3.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  permission_handler: ^10.4.4
  cloud_firestore: ^4.14.0
  firebase_core: ^2.18.0
  mysql_client: ^0.0.27
  webview_flutter: ^4.4.2  # or the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true