name: jam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  google_maps_flutter: ^2.2.3
  flutter_typeahead: ^4.1.0
  http: ^1.3.0   # Updated from ^0.13.5 to ^1.3.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  permission_handler: ^10.4.4  # or the latest version
  cloud_firestore: ^4.14.0  # Use the latest version
  firebase_core: ^2.18.0  # Use the current latest stable version
  test_api: ^0.7.4
  mysql1: ^0.20.0
  mysql_dart: ^1.0.0
  mysql_client: ^0.0.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  